# Copyright 2024 QuantPod Contributors
# SPDX-License-Identifier: Apache-2.0

"""
TextGrad-inspired backward pass on trading decision chains.

After losing trades, propagates textual critiques backward through the
decision chain (signal → regime → strategy → sizing) to identify which
node's prompt caused the failure, and proposes targeted prompt updates.

Paper: TextGrad (Yuksekgonul et al., Nature 2024) — https://arxiv.org/abs/2406.07496

Implementation note:
  We implement the TextGrad concept (textual backpropagation) without
  requiring the textgrad package. The backward pass is a structured
  LLM call via litellm that generates per-node critiques. This avoids
  a hard dependency while preserving the core idea: loss attribution
  through the computation graph via natural language gradients.

  All LLM calls are offline (post-market), never in the execution path.

Safety:
  - Prompt changes are PROPOSALS (status='proposed'), never auto-applied
  - Require OPRO validation or human review to become 'testing'
  - Must survive 1 week of paper trading to become 'active'
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any

from loguru import logger

from quantstack.optimization.credit_assignment import CreditAssigner, StepCredit


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class DecisionNode:
    """One step in the trading decision chain."""
    name: str            # "signal_collection", "regime_classification", "strategy_selection", "position_sizing"
    prompt_text: str     # Current prompt/rules for this node
    output_text: str     # What this node produced for this trade
    version: int = 0


@dataclass
class PromptProposal:
    """A proposed prompt update generated by the backward pass."""
    proposal_id: str
    node_name: str
    current_version: int
    proposed_text: str
    critique: str
    trade_id: int
    status: str = "proposed"  # proposed → testing → active → retired
    created_at: str = ""


PROMPT_CRITIQUES_TABLE = "prompt_critiques"
PROMPT_VERSIONS_TABLE = "prompt_versions"

# Node names in the decision chain
CHAIN_NODES = (
    "signal_collection",
    "regime_classification",
    "strategy_selection",
    "position_sizing",
)

# Map step_type (credit) to node_name (textgrad)
STEP_TO_NODE = {
    "signal": "signal_collection",
    "regime": "regime_classification",
    "strategy_selection": "strategy_selection",
    "sizing": "position_sizing",
    "debate": "strategy_selection",  # debate critiques feed into strategy selection
}


# ---------------------------------------------------------------------------
# TextGradOptimizer
# ---------------------------------------------------------------------------

class TextGradOptimizer:
    """Textual backpropagation over trading decision chains.

    Usage:
        opt = TextGradOptimizer(conn)
        proposals = opt.run_daily(date.today())  # process all losing trades
    """

    def __init__(
        self,
        conn: Any,
        engine: str = "claude-sonnet-4-20250514",
    ) -> None:
        self._conn = conn
        self._engine = engine
        self._credit_assigner = CreditAssigner(conn)

    # ------------------------------------------------------------------
    # Chain reconstruction
    # ------------------------------------------------------------------

    def build_chain(self, trade_context: dict) -> list[DecisionNode]:
        """Reconstruct the decision chain from trade context.

        In a full implementation, this would read from decision_events +
        signal_snapshots tables. For now, we build from the trade context
        dict which captures the key outputs at each step.
        """
        nodes = []

        nodes.append(DecisionNode(
            name="signal_collection",
            prompt_text="SignalEngine: 15 collectors, deterministic",
            output_text=trade_context.get("signals_summary", "no signals recorded"),
        ))

        nodes.append(DecisionNode(
            name="regime_classification",
            prompt_text="ADX/ATR trend + vol classification",
            output_text=(
                f"regime={trade_context.get('regime_at_entry', 'unknown')}, "
                f"exit_regime={trade_context.get('regime_at_exit', 'unknown')}"
            ),
        ))

        nodes.append(DecisionNode(
            name="strategy_selection",
            prompt_text=f"Strategy: {trade_context.get('strategy_id', 'unknown')}",
            output_text=(
                f"strategy={trade_context.get('strategy_id', 'unknown')}, "
                f"affinity={trade_context.get('strategy_regime_affinity', 0.5):.2f}"
            ),
        ))

        nodes.append(DecisionNode(
            name="position_sizing",
            prompt_text="Size based on conviction + vol",
            output_text=(
                f"size={trade_context.get('position_size', 'half')}, "
                f"conviction={trade_context.get('conviction', 0.5):.0%}"
            ),
        ))

        return nodes

    # ------------------------------------------------------------------
    # Backward pass (textual critique generation)
    # ------------------------------------------------------------------

    def backward_pass(
        self,
        chain: list[DecisionNode],
        loss_context: str,
        worst_step: StepCredit | None = None,
    ) -> dict[str, str]:
        """Generate per-node textual critiques via LLM.

        If worst_step is provided, focuses the critique on that node.
        Returns {node_name: critique_text}.

        Uses litellm for LLM calls. Falls back to heuristic critiques
        if litellm is unavailable or the call fails.
        """
        target_node = STEP_TO_NODE.get(
            worst_step.step_type, ""
        ) if worst_step else ""

        critiques = {}

        for node in chain:
            if target_node and node.name != target_node:
                # Skip non-target nodes to save LLM calls
                critiques[node.name] = ""
                continue

            critique = self._generate_critique(node, loss_context, worst_step)
            critiques[node.name] = critique

        return critiques

    def _generate_critique(
        self,
        node: DecisionNode,
        loss_context: str,
        worst_step: StepCredit | None,
    ) -> str:
        """Generate a textual critique for a single node via LLM."""
        try:
            import litellm

            prompt = (
                f"You are analyzing a losing trade to identify what went wrong at "
                f"the '{node.name}' step of the decision chain.\n\n"
                f"## Node: {node.name}\n"
                f"Current rules/prompt: {node.prompt_text}\n"
                f"Output at decision time: {node.output_text}\n\n"
                f"## Trade outcome\n{loss_context}\n\n"
            )
            if worst_step:
                prompt += (
                    f"## Credit assignment indicates this step is most culpable\n"
                    f"Evidence: {worst_step.evidence}\n"
                    f"Credit score: {worst_step.credit_score:.2f}\n\n"
                )
            prompt += (
                "Generate a concise critique (2-3 sentences) of what this step "
                "did wrong and what specific change to its rules/prompt would "
                "prevent this type of loss. Be specific and actionable."
            )

            response = litellm.completion(
                model=self._engine,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=500,
                temperature=0.3,
            )
            return response.choices[0].message.content.strip()

        except ImportError:
            logger.debug("[TextGrad] litellm not available, using heuristic critique")
            return self._heuristic_critique(node, worst_step)
        except Exception as exc:
            logger.warning(f"[TextGrad] LLM critique failed for {node.name}: {exc}")
            return self._heuristic_critique(node, worst_step)

    @staticmethod
    def _heuristic_critique(node: DecisionNode, worst_step: StepCredit | None) -> str:
        """Fallback critique when LLM is unavailable."""
        if worst_step:
            return f"[heuristic] {node.name}: {worst_step.evidence}"
        return f"[heuristic] {node.name}: Review rules; trade lost money."

    # ------------------------------------------------------------------
    # Proposal generation
    # ------------------------------------------------------------------

    def propose_prompt_update(
        self,
        node_name: str,
        critique: str,
        trade_id: int = 0,
    ) -> PromptProposal | None:
        """Store a prompt critique as a proposal. Does NOT apply it."""
        if not critique or critique.startswith("[heuristic]"):
            return None  # Don't store heuristic fallbacks

        proposal = PromptProposal(
            proposal_id=str(uuid.uuid4()),
            node_name=node_name,
            current_version=0,
            proposed_text="",  # Filled by OPRO when promoting
            critique=critique,
            trade_id=trade_id,
            status="proposed",
            created_at=datetime.now().isoformat(),
        )

        try:
            self._conn.execute(
                f"INSERT INTO {PROMPT_CRITIQUES_TABLE} "
                f"(id, trade_id, node_name, critique, proposed_edit) "
                f"VALUES (nextval('prompt_critiques_seq'), ?, ?, ?, ?)",
                [trade_id, node_name, critique, ""],
            )
        except Exception as exc:
            logger.warning(f"[TextGrad] Failed to persist critique: {exc}")

        return proposal

    # ------------------------------------------------------------------
    # Daily batch
    # ------------------------------------------------------------------

    def run_daily(
        self,
        run_date: date,
        losing_trades: list[dict] | None = None,
    ) -> list[PromptProposal]:
        """Process all losing trades from a given date.

        Args:
            run_date: Date to process (trades closed on this date).
            losing_trades: Optional pre-fetched list. If None, queries DB.

        Returns list of PromptProposals (may be empty if no losses).
        """
        if losing_trades is None:
            losing_trades = self._fetch_losing_trades(run_date)

        if not losing_trades:
            logger.info(f"[TextGrad] No losing trades on {run_date}, nothing to process")
            return []

        proposals = []
        for trade in losing_trades:
            try:
                # Build chain from trade context
                chain = self.build_chain(trade)

                # Get credit assignment for targeting
                credits = self._credit_assigner.assign_heuristic(trade)
                worst = CreditAssigner.get_worst_step(credits)

                # Build loss context string
                loss_context = (
                    f"Symbol: {trade.get('symbol', '?')}\n"
                    f"Strategy: {trade.get('strategy_id', '?')}\n"
                    f"P&L: {trade.get('realized_pnl_pct', 0):.1f}%\n"
                    f"Regime: {trade.get('regime_at_entry', '?')} → "
                    f"{trade.get('regime_at_exit', '?')}\n"
                    f"Conviction: {trade.get('conviction', 0):.0%}\n"
                    f"Size: {trade.get('position_size', '?')}"
                )

                # Backward pass
                critiques = self.backward_pass(chain, loss_context, worst)

                # Generate proposals for non-empty critiques
                for node_name, critique in critiques.items():
                    if critique:
                        proposal = self.propose_prompt_update(
                            node_name, critique,
                            trade_id=trade.get("trade_id", 0),
                        )
                        if proposal:
                            proposals.append(proposal)

            except Exception as exc:
                logger.warning(
                    f"[TextGrad] Failed to process trade {trade.get('trade_id', '?')}: {exc}"
                )

        logger.info(f"[TextGrad] Generated {len(proposals)} proposals from {len(losing_trades)} losing trades")
        return proposals

    def _fetch_losing_trades(self, run_date: date) -> list[dict]:
        """Fetch losing trades from strategy_outcomes for a given date."""
        try:
            rows = self._conn.execute(
                "SELECT id, strategy_id, symbol, regime_at_entry, "
                "entry_price, exit_price, realized_pnl_pct, closed_at "
                "FROM strategy_outcomes "
                "WHERE realized_pnl_pct < -1.0 "
                "AND CAST(closed_at AS DATE) = ? "
                "ORDER BY realized_pnl_pct ASC",
                [str(run_date)],
            ).fetchall()
            return [
                {
                    "trade_id": row[0],
                    "strategy_id": row[1],
                    "symbol": row[2],
                    "regime_at_entry": row[3],
                    "regime_at_exit": "unknown",  # Not stored in strategy_outcomes
                    "realized_pnl_pct": row[6],
                    "conviction": 0.5,
                    "position_size": "half",
                    "signals_present": True,
                    "strategy_regime_affinity": 0.5,
                    "signals_summary": "",
                }
                for row in rows
            ]
        except Exception as exc:
            logger.warning(f"[TextGrad] Failed to fetch losing trades: {exc}")
            return []

    # NOTE: Research chain critique (build_research_chain, critique_research,
    # _identify_research_weakness) removed — premature with <25 research runs/month.
    # Re-add when research runs 100+/month and backtest Sharpe is a stable signal.
    # See docs/OPTIMIZATION.md "When to Revisit" section.
