# Copyright 2024 QuantPod Contributors
# SPDX-License-Identifier: Apache-2.0

"""
MCP Bridge - CrewAI tools that wrap MCP server calls.

Provides CrewAI-compatible tools that call the QuantCore and eTrade MCP servers.

QuantCore Tools:
- Market Data: fetch_market_data, load_market_data, list_stored_symbols, get_symbol_snapshot
- Technical Analysis: compute_indicators, compute_all_features, list_available_indicators
- Backtesting: run_backtest, get_backtest_metrics, run_monte_carlo, run_walkforward
- Statistical: run_adf_test, compute_alpha_decay, compute_information_coefficient
- Options: price_option, compute_greeks, compute_implied_vol, analyze_option_structure
- Risk: compute_position_size, compute_var, stress_test_portfolio, check_risk_limits
- Market: get_market_regime_snapshot, analyze_volume_profile, get_trading_calendar

eTrade Tools:
- Quotes: get_quote, get_option_chains
- Orders: preview_order, place_order
- Account: get_positions, get_account_balance
"""

# Bridge class and helpers
from ._bridge import MCPBridge, _run_async, get_bridge

# All Pydantic input schemas
from ._schemas import (
    ADFTestInput,
    AlphaDecayInput,
    AnalyzeOptionStructureInput,
    BacktestInput,
    BacktestMetricsInput,
    BalanceInput,
    ComputeGreeksInput,
    ComputeOptionChainInput,
    DiagnoseSignalInput,
    EmptyInput,
    EventCalendarInput,
    FetchMarketDataInput,
    ICInput,
    ImpliedVolInput,
    IndicatorsInput,
    LiquidityInput,
    LoadMarketDataInput,
    MarketRegimeSnapshotInput,
    MaxDrawdownInput,
    MonteCarloInput,
    MultiLegPriceInput,
    OptionChainInput,
    PlaceOrderInput,
    PortfolioStatsInput,
    PositionSizeInput,
    PositionsInput,
    PreviewOrderInput,
    PriceOptionInput,
    QuoteInput,
    RiskLimitsInput,
    ScoreTradeInput,
    ScreenerInput,
    SimulateTradeInput,
    StressTestInput,
    SymbolInput,
    SymbolSnapshotInput,
    TradeTemplateInput,
    TradingCalendarInput,
    ValidateSignalInput,
    ValidateTradeInput,
    VaRInput,
    VolumeProfileInput,
    WalkForwardInput,
)

# All factory functions
from ._factories import (
    analyze_liquidity_tool,
    analyze_option_structure_tool,
    analyze_volume_profile_tool,
    check_risk_limits_tool,
    compute_all_features_tool,
    compute_alpha_decay_tool,
    compute_greeks_tool,
    compute_implied_vol_tool,
    compute_indicators_tool,
    compute_information_coefficient_tool,
    compute_max_drawdown_tool,
    compute_multi_leg_price_tool,
    compute_option_chain_tool,
    compute_portfolio_stats_tool,
    compute_position_size_tool,
    compute_var_tool,
    diagnose_signal_tool,
    fetch_market_data_tool,
    generate_trade_template_tool,
    get_account_balance_tool,
    get_backtest_metrics_tool,
    get_event_calendar_tool,
    get_market_regime_snapshot_tool,
    get_option_chains_tool,
    get_positions_tool,
    get_quote_tool,
    get_symbol_snapshot_tool,
    get_trading_calendar_tool,
    list_available_indicators_tool,
    list_stored_symbols_tool,
    load_market_data_tool,
    place_order_tool,
    preview_order_tool,
    price_option_tool,
    run_adf_test_tool,
    run_backtest_tool,
    run_monte_carlo_tool,
    run_screener_tool,
    run_walkforward_tool,
    score_trade_structure_tool,
    simulate_trade_outcome_tool,
    stress_test_portfolio_tool,
    validate_signal_tool,
    validate_trade_tool,
)

# Tool classes - eTrade
from .tools_etrade import (
    GetAccountBalanceTool,
    GetOptionChainsTool,
    GetPositionsTool,
    GetQuoteTool,
    PlaceOrderTool,
    PreviewOrderTool,
)

# Tool classes - Data
from .tools_data import (
    FetchMarketDataTool,
    GetSymbolSnapshotTool,
    ListStoredSymbolsTool,
    LoadMarketDataTool,
)

# Tool classes - Analysis (technical, backtesting, statistical, options)
from .tools_analysis import (
    AnalyzeOptionStructureTool,
    ComputeAllFeaturesTool,
    ComputeAlphaDecayTool,
    ComputeGreeksTool,
    ComputeImpliedVolTool,
    ComputeIndicatorsTool,
    ComputeInformationCoefficientTool,
    ComputeMultiLegPriceTool,
    ComputeOptionChainTool,
    DiagnoseSignalTool,
    GetBacktestMetricsTool,
    ListAvailableIndicatorsTool,
    PriceOptionTool,
    RunADFTestTool,
    RunBacktestTool,
    RunMonteCarloTool,
    RunWalkForwardTool,
    ValidateSignalTool,
)

# Tool classes - Risk
from .tools_risk import (
    AnalyzeLiquidityTool,
    CheckRiskLimitsTool,
    ComputeMaxDrawdownTool,
    ComputePortfolioStatsTool,
    ComputePositionSizeTool,
    ComputeVaRTool,
    StressTestPortfolioTool,
)

# Tool classes - Market/Regime and Trade
from .tools_market import (
    AnalyzeVolumeProfileTool,
    GenerateTradeTemplateTool,
    GetEventCalendarTool,
    GetMarketRegimeSnapshotTool,
    GetTradingCalendarTool,
    RunScreenerTool,
    ScoreTradeStructureTool,
    SimulateTradeOutcomeTool,
    ValidateTradeTool,
)

__all__ = [
    # Bridge
    "MCPBridge",
    "get_bridge",
    "_run_async",
    # Input schemas
    "QuoteInput",
    "OptionChainInput",
    "PreviewOrderInput",
    "PlaceOrderInput",
    "PositionsInput",
    "BalanceInput",
    "FetchMarketDataInput",
    "LoadMarketDataInput",
    "EmptyInput",
    "MarketRegimeSnapshotInput",
    "SymbolInput",
    "IndicatorsInput",
    "BacktestInput",
    "BacktestMetricsInput",
    "MonteCarloInput",
    "WalkForwardInput",
    "ADFTestInput",
    "AlphaDecayInput",
    "ICInput",
    "ValidateSignalInput",
    "DiagnoseSignalInput",
    "PriceOptionInput",
    "ComputeGreeksInput",
    "ImpliedVolInput",
    "AnalyzeOptionStructureInput",
    "ComputeOptionChainInput",
    "MultiLegPriceInput",
    "PositionSizeInput",
    "MaxDrawdownInput",
    "PortfolioStatsInput",
    "VaRInput",
    "StressTestInput",
    "RiskLimitsInput",
    "LiquidityInput",
    "SymbolSnapshotInput",
    "VolumeProfileInput",
    "TradingCalendarInput",
    "EventCalendarInput",
    "TradeTemplateInput",
    "ValidateTradeInput",
    "ScoreTradeInput",
    "SimulateTradeInput",
    "ScreenerInput",
    # eTrade Tool classes
    "GetQuoteTool",
    "GetOptionChainsTool",
    "PreviewOrderTool",
    "PlaceOrderTool",
    "GetPositionsTool",
    "GetAccountBalanceTool",
    # Data Tool classes
    "FetchMarketDataTool",
    "LoadMarketDataTool",
    "ListStoredSymbolsTool",
    "GetSymbolSnapshotTool",
    # Analysis Tool classes
    "ComputeIndicatorsTool",
    "ComputeAllFeaturesTool",
    "ListAvailableIndicatorsTool",
    "RunBacktestTool",
    "GetBacktestMetricsTool",
    "RunMonteCarloTool",
    "RunWalkForwardTool",
    "RunADFTestTool",
    "ComputeAlphaDecayTool",
    "ComputeInformationCoefficientTool",
    "ValidateSignalTool",
    "DiagnoseSignalTool",
    "PriceOptionTool",
    "ComputeGreeksTool",
    "ComputeImpliedVolTool",
    "AnalyzeOptionStructureTool",
    "ComputeOptionChainTool",
    "ComputeMultiLegPriceTool",
    # Risk Tool classes
    "ComputePositionSizeTool",
    "ComputeMaxDrawdownTool",
    "ComputePortfolioStatsTool",
    "ComputeVaRTool",
    "StressTestPortfolioTool",
    "CheckRiskLimitsTool",
    "AnalyzeLiquidityTool",
    # Market Tool classes
    "GetMarketRegimeSnapshotTool",
    "AnalyzeVolumeProfileTool",
    "GetTradingCalendarTool",
    "GetEventCalendarTool",
    "GenerateTradeTemplateTool",
    "ValidateTradeTool",
    "ScoreTradeStructureTool",
    "SimulateTradeOutcomeTool",
    "RunScreenerTool",
    # Factory functions
    "get_quote_tool",
    "get_option_chains_tool",
    "preview_order_tool",
    "place_order_tool",
    "get_positions_tool",
    "get_account_balance_tool",
    "fetch_market_data_tool",
    "load_market_data_tool",
    "list_stored_symbols_tool",
    "get_symbol_snapshot_tool",
    "compute_indicators_tool",
    "compute_all_features_tool",
    "list_available_indicators_tool",
    "run_backtest_tool",
    "get_backtest_metrics_tool",
    "run_monte_carlo_tool",
    "run_walkforward_tool",
    "run_adf_test_tool",
    "compute_alpha_decay_tool",
    "compute_information_coefficient_tool",
    "validate_signal_tool",
    "diagnose_signal_tool",
    "price_option_tool",
    "compute_greeks_tool",
    "compute_implied_vol_tool",
    "analyze_option_structure_tool",
    "compute_option_chain_tool",
    "compute_multi_leg_price_tool",
    "compute_position_size_tool",
    "compute_max_drawdown_tool",
    "compute_portfolio_stats_tool",
    "compute_var_tool",
    "stress_test_portfolio_tool",
    "check_risk_limits_tool",
    "analyze_liquidity_tool",
    "get_market_regime_snapshot_tool",
    "analyze_volume_profile_tool",
    "get_trading_calendar_tool",
    "get_event_calendar_tool",
    "generate_trade_template_tool",
    "validate_trade_tool",
    "score_trade_structure_tool",
    "simulate_trade_outcome_tool",
    "run_screener_tool",
]
